### PR TITLE
Fix Ad height to comply with admob policy

### PR DESCRIPTION
**Pull request by mourjan**
As mentioned before, it is against admob/adsense policy to change layout after ads are loaded so it doesn't drive any mistaken clicks or interactions.
So basically, here is in summary what was done:
1- set NativeExpressAdView layout height to the adSize's height
2- notify dataset change right after ad setup and not after ad loaded
3- hide ad list row in case of ad load failure

Also, project is compatible with minSdkVersion 9

### CODE REVIEW

**Comment by kot331107** [comment]
Hi
Thanks for a great contribution! I'll merge it with experimental, test, then pull to master.

**Comment by kot331107** [comment]
Yeah, I guess you absolutely right about the policies: https://support.google.com/admob/answer/2936217.

**Comment by mourjan** [comment]
Glad I could be of help, but do note that this fix implies only to Native Express views.

**Comment by kot331107** [comment]
@mourjan sure, I have noticed. I think I'll fix the Advanced Native presentation a bit later. Also please review my latest changes to the branch **experimental** because I 've changed your code a bit: I've changed incrementation/decrementation of the field **mNoOfFetchedAds** to a prefix form instead of postfix one. I guess we should pass an updated value of the **mNoOfFetchedAds** to the method **notifyObserversOfAdSizeChange**. Actually It doesn't influence on result **at the moment** because listener doesn't use this value but it could use it further. Waiting for your accept.

**Comment by mourjan** [comment]
@kot331107 you are 100% right, I noticed it right after I submit it the pull request but didn't fix cause it didn't have any side effects and figured that I would fix with a next contribution.
Anyways, everything looks great.
Also, after I finish up with what I have on hand, I will make sure to continue in contributing. especially after I receive some answers about admobs' policies against having multiple native ad templates in one list (multiple unit ids and sizes)
Finally, hope it won't be long for next release so I can include it in my upcoming update release as a gradle library.
Cheers

**Comment by kot331107** [comment]
@mourjan Great, I'll merge to master then :) Sure, we can definetely postpone the gradle release till you get an updated info about Admob policies. As far as I know Admob policy allows to show infinite count of ads in one list. The main requirements here are:
1. Don't show more than one ad block per scrolling screen so users of this library should take it into account when they set the count of list items between ad blocks and so on)
2. Don't load all the ads at one time, use lazy loading when scrolling down. This lib satisfies it as I understand :+1: 
The main question for me at the moment is ** should we use separate unit id for each ad block in the list or not?**

**Comment by mourjan** [comment]
@kot331107 totally with you on the requirements as they totally comply with admob's listed policies, its just that adsense are having a hangout today to talk about their policies and hopefully they'll answer my questions.

On the other hand, having multiple unit ids is a must in future releases, given the fact that it will provide a flexibility with ad sizes, for example, beginning of list would have a small ad, along the list the next ad would be medium and maybe another medium and near the end it would be a large ad (which might serve video install ads)

But do go ahead with the gradle release, for this fix is crucial to developers/publishers who might risk getting their account suspended.

**Comment by kot331107** [comment]
> and near the end it would be a large ad (which might serve video install ads)

I guess we need improve admobadapter urgently :D

**Pull request merged**
